import jsPDF from "jspdf";
import type { AnalysisType } from "@/types";

export function exportAnalysisAsPDF(
  analysis: AnalysisType,
  documentName: string
): void {
  const doc = new jsPDF();
  let yPosition = 20;

  // Title
  doc.setFontSize(20);
  doc.text("KanoonScan Analysis Report", 20, yPosition);
  yPosition += 10;

  // Document name
  doc.setFontSize(12);
  doc.text(`Document: ${documentName}`, 20, yPosition);
  yPosition += 10;

  // Risk Score
  doc.setFontSize(16);
  doc.text(
    `Risk Score: ${analysis.riskScore}/100 (${analysis.riskLevel})`,
    20,
    yPosition
  );
  yPosition += 15;

  // Summary
  doc.setFontSize(12);
  doc.text("Summary:", 20, yPosition);
  yPosition += 7;
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(analysis.summary, 170);
  doc.text(summaryLines, 20, yPosition);
  yPosition += summaryLines.length * 5 + 10;

  // Clauses
  doc.setFontSize(14);
  doc.text("Flagged Clauses:", 20, yPosition);
  yPosition += 10;

  analysis.clauses.forEach((clause, index) => {
    if (yPosition > 270) {
      doc.addPage();
      yPosition = 20;
    }

    doc.setFontSize(11);
    doc.text(`${index + 1}. ${clause.title} [${clause.riskLevel}]`, 20, yPosition);
    yPosition += 7;

    doc.setFontSize(9);
    const explanationLines = doc.splitTextToSize(clause.explanation, 170);
    doc.text(explanationLines, 25, yPosition);
    yPosition += explanationLines.length * 5 + 8;
  });

  // Footer
  yPosition = 280;
  doc.setFontSize(8);
  doc.text(
    "Generated by KanoonScan - This is not legal advice. Consult a lawyer.",
    20,
    yPosition
  );

  // Download
  doc.save(`${documentName}_analysis.pdf`);
}
